[package]
name = "slide"
version = "0.1.0"
edition = "2024"

[dependencies]
# typewit = "1.11.0"


[features]
# default = ["std"]

std = ["alloc"]
alloc = []

# Enabling this feature tells the crate to optimize for file size.
opt_size = []
