[package]
name = "slide"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = ["std"]

std = ["alloc"]
alloc = []

# Enabling this feature tells the crate to optimize for file size.
opt_size = []

# Enabling this forces slides to be index-based.
force_index = []
